[project]
name = "dbt-zero-to-hero"
version = "1.10.0"
requires-python = ">=3.10,<=3.13"
dependencies = [
    "dbt-core~=1.10.0",
    "dbt-snowflake~=1.10.0",
    "dbt-autofix~=0.12.10",
    "dagster-dbt~=0.28.0",
    "dagster-webserver~=1.12.0",
]