[project]
name = "dbt-bootcamp"
version = "1.11.0"
requires-python = ">=3.10,<3.14"
dependencies = [
    "dbt-core~=1.11.0",
    "dbt-snowflake~=1.11.0",
    "dbt-autofix~=0.18.0",
    "dagster-dbt~=0.28.0",
    "dagster-webserver~=1.12.0",
]