# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test App

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'nordquant/complete-dbt-bootcamp-zero-to-hero'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create dbt profile
      env:
        PROFILES_YML: ${{ secrets.PROFILES_YML }}
      run: |
        mkdir -p ~/.dbt
        echo "$PROFILES_YML" > ~/.dbt/profiles.yml
    - name: Execute dbt debug
      run: |
        cd dbtlearn
        dbt debug
    - name: Install packages
      run: |
        cd dbtlearn
        dbt deps
    - name: dbt build
      run: |
        cd dbtlearn
        dbt build
    - name: dbt docs generate
      run: |
        cd dbtlearn
        dbt docs generate

