# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test App

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # 2 AM CET (1 AM UTC)

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'nordquant/complete-dbt-bootcamp-zero-to-hero'
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10"]
        runs-on: [ubuntu-latest, ubuntu-latest-arm64]
    env:
      full_test_python: "3.12"
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --python ${{ matrix.python-version }}
    - name: Create dbt profile
      env:
        PROFILES_YML: ${{ secrets.PROFILES_YML }}
      run: |
        mkdir -p ~/.dbt
        echo "$PROFILES_YML" > ~/.dbt/profiles.yml
    - name: Execute dbt debug
      run: |
        cd airbnb
        uv run dbt debug
    - name: Install packages
      run: |
        cd airbnb
        uv run dbt deps
    - name: dbt build
      if: matrix.python-version == env.full_test_python && matrix.runs-on == 'ubuntu-latest'
      run: |
        cd airbnb
        uv run dbt build
    - name: dbt docs generate
      if: matrix.python-version == env.full_test_python && matrix.runs-on == 'ubuntu-latest'
      run: |
        cd airbnb
        uv run dbt docs generate
    - name: Install dbt fusion
      if: matrix.python-version == env.full_test_python && matrix.runs-on == 'ubuntu-latest'
      run: |
        curl -fsSL https://public.cdn.getdbt.com/fs/install/install.sh | sh -s -- --update
    - name: dbtf build (Fusion)
      if: matrix.python-version == env.full_test_python && matrix.runs-on == 'ubuntu-latest'
      run: |
        cd airbnb
        /home/runner/.local/bin/dbt build

